services:
  db:
    image: mysql:8.0
    container_name: auth_db_container
    env_file: .env # Bilgileri direkt .env dosyasından çek dedik
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: auth_api_container
    ports:
      - "3000:3000"
    env_file: .env # Bilgileri direkt .env dosyasından çek dedik
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: