version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: auth_db_container
    restart: always
    # .env dosyasındaki MYSQL_ROOT_PASSWORD gibi değişkenleri buraya eşliyoruz
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - auth_network

  api:
    build: .
    container_name: auth_api_container
    restart: always
    # .env dosyasını otomatik olarak bu konteynerin içine yükler
    env_file:
      - .env
    depends_on:
      - db
    # EKLENEN KISIM 1: VS Code'un bağlanacağı debug portunu dışarı açıyoruz
    ports:
      - "9229:9229"
    # EKLENEN KISIM 2: Node.js'i debug modunda başlatıyoruz. 
    # Not: Eğer ana dosyan index.js değilse (örneğin app.js veya server.js ise) aşağıyı ona göre değiştir.
    command: node --inspect=0.0.0.0:9229 index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - auth_network
networks:
  auth_network:
    external: true

volumes:
  db_data: